# Generated by Django 5.2.11 on 2026-02-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=66)),
                ('slug', models.TextField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('cat_img', models.ImageField(upload_to='photos/category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
